### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by aqw** [psyinfra/htcondor_preview#1]

**Comment by jonamfischer** [comment]
By this you mean the usage and help info right?

**Comment by aqw** [comment]
Yes, and providing that info as a manual page as well.

There's two approaches: writing the manpage by hand in troff (as is done in `htcompact` and `niiview`) or use a help2man converter, which taked the output of `--help` and generates a manpage from that. I have no experience with the latter option, but many projects do that so they don't have to keep the two copies in sync with changes.
